////Generated by Prefab3D 2.143, Wed Jan 21 16:38:51 GMT+0300 2015. www.closier.nl/prefab
package data {

	import away3d.core.base.Geometry;
	import data.ASDReader;

	public class Box15Data {

		[Embed(source="asd/Box15Data.asd", mimeType="application/octet-stream")]
		private var Box15DataASD:Class;

		public function get geometryData():Geometry
		{
			return ASDReader.decodeGeometry(new Box15DataASD());
		}

	}
}